### ISSUE TITLE
an error that doesn't exist when importing xmtl 

### ISSUE THREAD

**Issue by MateElPepitoQuerido** [Lixquid/app-unexpected-keyboard-layout-editor#14]
When trying to import a file it doesn't matter if it's even the officer comes out to me that there's an error in a line that doesn't exist ("line 0")

**Comment by Lixquid** [comment]
Hi, I think this is a bug report about a failure to import XML?

Do you have an example of the failing XML?

**Comment by MateElPepitoQuerido** [comment]
hi, the xtml is one of the official ones from the github of the unexpected
keyboard, even so I tried one that left the page and I also got the error,
both are in the app

**Comment by Lixquid** [comment]
This should now be fixed; there was an issue with the deploy job that put this code live which meant it was stuck on an old version. Sorry for the issues!
