### ISSUE TITLE
"Enter" and "End" uses the same icon, making them indiscernible

### ISSUE THREAD

**Issue by kennethso168** [Lixquid/app-unexpected-keyboard-layout-editor#15]
![image](https://github.com/Lixquid/app-unexpected-keyboard-layout-editor/assets/5262487/8013ae43-0f9e-4040-827c-f51b022a838a)

Perhaps it is better to use [`bi-arrow-return-left`](https://icons.getbootstrap.com/icons/arrow-return-left/) for the Enter key? It also matches the Enter icon as shown on Unexpected Keyboard.

![image](https://github.com/Lixquid/app-unexpected-keyboard-layout-editor/assets/5262487/dda5c661-720e-459d-b473-05ecd886a814)
![image](https://f-droid.org/repo/juloo.keyboard2/en-US/phoneScreenshots/2.png)

**Comment by Lixquid** [comment]
Nice catch!
